# Generated by Django 4.2 on 2023-05-16 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations', '0002_habilitations_created_at_habilitations_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitations',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habilitations',
            name='updated_by',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='habilitations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='habilitations',
            name='created_by',
            field=models.TextField(null=True),
        ),
    ]
