# Generated by Django 4.2 on 2023-05-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations', '0003_habilitations_updated_at_habilitations_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilitations',
            name='libelle',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
