# Generated by Django 4.2 on 2023-05-16 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('specialites', '0001_initial'),
    ]

    operations = [
        
    ]
