# Generated by Django 4.2 on 2023-05-17 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('specialites', '0007_remove_specialites_users_specialites_description_and_more'),
    ]

    operations = [
        
    ]
