# Generated by Django 4.2 on 2023-05-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialites', '0005_alter_specialites_libelle'),
        ('specialites', '0008_remove_specialites_users_specialites_description_and_more'),
    ]

    operations = [
    ]
