# Generated by Django 4.2 on 2023-05-19 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('specialites', '0009_merge_20230519_1152'),
    ]

    operations = [
        
    ]
