# Generated by Django 4.2.1 on 2023-05-22 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('specialites', '0010_remove_specialites_users_specialites_description_and_more'),
    ]

    operations = [
    ]
