# Generated by Django 4.2 on 2023-05-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendas', '0004_remove_agendas_date_remove_agendas_heure_and_more'),
        ('personnes', '0001_initial'),
        ('specialites', '0002_remove_specialites_users_specialites_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.TextField(null=True)),
                ('agendas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', related_query_name='rendezvous', to='agendas.agendas')),
                ('personnes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', related_query_name='rendezvous', to='personnes.personnes')),
                ('specialites', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', related_query_name='rendezvous', to='specialites.specialites')),
                    
            ],
        ),
    ]
