# Generated by Django 4.2 on 2023-05-16 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0002_alter_rendezvous_statuts'),
    ]

    operations = [
    ]
