# Generated by Django 4.2.1 on 2023-05-19 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statut', '0001_initial'),
        ('rendezvous', '0003_rendezvous_statuts'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='statut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', related_query_name='rendezvous', to='statut.statut'),
        ),
    ]
