# Generated by Django 4.2.1 on 2023-05-24 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0009_remove_agendas_personnes'),
        ('personnes', '0003_alter_personnes_nom_alter_personnes_telephone'),
        ('specialites', '0013_remove_specialites_users_specialites_description_and_more'),
        ('statut', '0002_alter_statut_libelle'),
        ('rendezvous', '0004_rendezvous_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='agendas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.agendas'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='personnes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnes.personnes'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='specialites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialites.specialites'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statut.statut'),
        ),
    ]
