# Generated by Django 4.2.1 on 2023-05-24 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialites', '0018_remove_specialites_users_specialites_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendas', '0009_remove_agendas_personnes'),
        ('statut', '0003_alter_statut_libelle'),
        ('rendezvous', '0005_alter_rendezvous_agendas_alter_rendezvous_personnes_and_more'),
    ]

    operations = [
        
    ]
