# Generated by Django 4.2.1 on 2023-05-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0008_remove_rendezvous_personnes_rendezvous_users_and_more'),
    ]

    operations = [
    ]
