# Generated by Django 4.2.1 on 2023-05-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0006_remove_rendezvous_personnes_rendezvous_users_and_more'),
        ('rendezvous', '0009_remove_rendezvous_personnes'),
    ]

    operations = [
    ]
