# Generated by Django 4.2 on 2023-05-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
