# Generated by Django 4.2 on 2023-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenpatients', '0002_alter_examenpatients_resultat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenpatients',
            name='resultat',
            field=models.TextField(),
        ),
    ]
