# Generated by Django 4.2.1 on 2023-05-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statut', '0002_alter_statut_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statut',
            name='libelle',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
