# Generated by Django 4.2 on 2023-05-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_users_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='telephone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
