# Generated by Django 4.2 on 2023-05-24 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescriptions', '0003_alter_prescriptions_personnes'),
    ]

    operations = [
       
    
        migrations.AddField(
            model_name='prescriptions',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
