# Generated by Django 4.2 on 2023-05-29 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossierpatients', '0004_alter_dossierpatients_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescriptions', '0004_remove_prescriptions_personnes_prescriptions_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='dossierpatients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', related_query_name='prescription', to='dossierpatients.dossierpatients'),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', related_query_name='prescription', to=settings.AUTH_USER_MODEL),
        ),
    ]
