# Generated by Django 4.2 on 2023-06-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_remove_prescriptions_personnes_and_more'),
        ('prescriptions', '0005_prescriptions_dossierpatients_and_more'),
    ]

    operations = [
    ]
