# Generated by Django 4.2 on 2023-06-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_merge_20230602_1010'),
    ]

    operations = [
    ]
