# Generated by Django 4.2 on 2023-06-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0007_remove_prescriptions_personnes'),
    ]

    operations = [
      
    ]
