# Generated by Django 4.2 on 2023-06-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0008_remove_prescriptions_personnes'),
    ]

    operations = [
       
    ]
