# Generated by Django 4.2 on 2023-06-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0009_remove_prescriptions_personnes'),
    ]

    operations = [
       
    ]
