# Generated by Django 4.2.1 on 2023-05-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecins',
            name='adresse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medecins',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='medecins',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medecins',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medecins',
            name='telephone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
