# Generated by Django 4.2.1 on 2023-05-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendas',
            old_name='idagenda',
            new_name='id',
        ),
    ]
