# Generated by Django 4.2.1 on 2023-05-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_rename_idagenda_agendas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
