# Generated by Django 4.2 on 2023-05-16 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('heures', '0001_initial'),
        ('jours', '0001_initial'),
        ('agendas', '0003_alter_agendas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendas',
            name='date',
        ),
        migrations.RemoveField(
            model_name='agendas',
            name='heure',
        ),
        migrations.AddField(
            model_name='agendas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendas',
            name='created_by',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agendas',
            name='disponibilite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendas',
            name='heures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', related_query_name='agenda', to='heures.heures'),
        ),
        migrations.AddField(
            model_name='agendas',
            name='jours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', related_query_name='agenda', to='jours.jours'),
        ),
    ]
