# Generated by Django 4.2 on 2023-05-16 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_remove_agendas_date_remove_agendas_heure_and_more'),
        ('medecins', '0001_initial'),
        ('personnes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendas',
            name='medecins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', related_query_name='agenda', to='medecins.medecins'),
        ),
        migrations.AddField(
            model_name='agendas',
            name='personnes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', related_query_name='agenda', to='personnes.personnes'),
        ),
        migrations.AddField(
            model_name='agendas',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendas',
            name='updated_by',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='agendas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
