# Generated by Django 4.2.1 on 2023-05-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0001_initial'),
        ('agendas', '0006_alter_agendas_jours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendas',
            name='medecins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', related_query_name='agenda', to='medecins.medecins'),
        ),
    ]
