# Generated by Django 4.2 on 2023-05-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jours', '0001_initial'),
        ('agendas', '0006_alter_agendas_jours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendas',
            name='jours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', related_query_name='agenda', to='jours.jours'),
        ),
    ]
