# Generated by Django 4.2.1 on 2023-05-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0007_alter_agendas_jours'),
        ('agendas', '0007_alter_agendas_medecins'),
    ]

    operations = [
    ]
