# Generated by Django 4.2.1 on 2023-05-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0008_merge_20230519_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendas',
            name='personnes',
        ),
    ]
