# Generated by Django 4.2 on 2023-06-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialites', '0030_remove_specialites_users_specialites_description_and_more'),
        ('agendas', '0011_agendas_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendas',
            name='specialites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', related_query_name='agenda', to='specialites.specialites'),
        ),
    ]
