# Generated by Django 4.2 on 2023-05-25 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossierpatients', '0002_alter_dossierpatients_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierpatients',
            name='personnes',
        ),
        migrations.AddField(
            model_name='dossierpatients',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossierpatients', related_query_name='dossierpatient', to=settings.AUTH_USER_MODEL),
        ),
    ]
