# Generated by Django 4.2 on 2023-05-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossierpatients', '0003_remove_dossierpatients_personnes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierpatients',
            name='numero',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
