# Generated by Django 4.2 on 2023-06-14 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossierpatients', '0004_alter_dossierpatients_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierpatients',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dossierpatients',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dossierpatients',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
