# Generated by Django 4.2 on 2023-05-16 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenoms', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=100)),
                ('ddn', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.TextField(null=True)),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnes', related_query_name='personne', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
