# Generated by Django 4.2.1 on 2023-05-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnes',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
