# Generated by Django 4.2.1 on 2023-05-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0002_alter_personnes_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnes',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personnes',
            name='telephone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
