# Generated by Django 4.2.1 on 2023-05-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0003_alter_personnes_nom_alter_personnes_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnes',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personnes',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
