# Generated by Django 4.2 on 2023-05-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0003_alter_personnes_email_alter_personnes_nom'),
        ('personnes', '0003_alter_personnes_nom_alter_personnes_telephone'),
    ]

    operations = [
    ]
