# Generated by Django 4.2 on 2023-05-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0004_merge_20230523_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnes',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
