# Generated by Django 4.2.1 on 2023-05-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0004_alter_personnes_email_alter_personnes_telephone'),
        ('personnes', '0005_alter_personnes_telephone'),
    ]

    operations = [
    ]
